version: '3.8'

volumes:
  mysql-volume-bottle:

services:
  bottle:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:5000"
    volumes:
      - ./src:/usr/src/app

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume-bottle:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: 'db'
      PMA_USER: 'root'
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
    - ${PMA_PORT}:80

